### ISSUE TITLE
Demo playback

### ISSUE THREAD

**Issue by esposm03** [taskinoz/Enhanced-Menu-Mod#1]
Hey, I found this mod, and was really looking forward to using the demo recording feature, however I didn't find any way to actually see the recorded demos! How do I do that?

**Comment by taskinoz** [comment]
There isn't and easy way to replay videos from in game, however you can use a custom config to kind a key to play the demo with the command:  
``bind "key" "playdemo DEMOFILENAME"``

You can find out how to add a custom config [here](https://www.youtube.com/watch?v=VReX_i140W8&feature=youtu.be) or [here](https://www.youtube.com/watch?v=32wD_O1Ss68)  
  
You can find the demos in your Titanfall 2 folder under the ``r2`` directory. The demo files will end with ``.dem``.

**Note:** don't include .dem in the command for playing the demo, and you can only activate the playback of a demo after loading a level

**Comment by esposm03** [comment]
Thanks!
