### ISSUE TITLE
Speedometer: Add support for MP or mention that is only available in SP

### ISSUE THREAD

**Issue by GeckoEidechse** [taskinoz/Enhanced-Menu-Mod#3]
Basically what the title says. I assumed speedometer would work for both SP and MP, so it took me longer than I'd like to admit trying to figure out why the speedometer doesn't work (in MP).

So I'd argue it would make sense to either  [update the README](https://github.com/taskinoz/Enhanced-Menu-Mod/blob/master/README.md?plain=1#L68) to clarify that the speedometer only works in SP, or better add support for MP if possible (would be highly appreciated <3)

**Comment by taskinoz** [comment]
I'll probably update the README to clarify that, thankyou.
You can get a pre-compiled version of the speedometer [here](https://github.com/taskinoz/Syampuuh-VPK-Builds/releases) in the future, if you need it again.

**Comment by GeckoEidechse** [comment]
Good to know and thanks for the link to pre-compiled mods <3

**Comment by taskinoz** [comment]
No problem
